---

- name: create aws tower instance
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    os: linux 
    instance_name: labguide
    dns_zone: pharriso.co.uk
    ami_id: ami-08f4717d06813bf00
    termination_protection: false
  roles:
    - aws_vpc
    - aws_instances
    - route53_record
